name: Test

on:
  push:
    branches:
    - main
  pull_request:
jobs:
  test:
    uses: lufia/workflows/.github/workflows/go-test.yml@77b285fcfe013c0e99b18ca23b0c9d575bd4327a # v0.8.0
    #with:
      # TODO(lufia): TestWaitDeadline is broken on Windows.
      #
      # Go 1.23 will ship CL 488675, high res timer on Windows,
      # so I guess that issue may be fixed.
      # https://github.com/golang/go/issues/44343
      #os-versions: '["ubuntu-22.04", "macos-13"]'
